let gods = [
    "Zeus",
    "Poseidon",
    "Hades",
    "Hera",
    "Ares",
    "Athena",
    "Hephaestus",
    "Hermes",
    "Demeter",
    "Dionysus",
    "Aphrodite",
    "Artemis",
    "Eros",
    "Pan",
    "Harmonia",
    "Hebe",
    "Nike",
    "Persephone",
    "Asclepius",
    "Hecate",
    "Bia",
    "Eris",
    "Deimos",
    "Phobos",
    "Kratos",
    "Alecto",
    "Megaera",
    "Tisiphone",
    "Vesta",
    "Thanatos",
    "Rhode",
    "Nyx",
    "Enyo",
    "Atropos,",
    "Clotho",
    "Lachesis",
    "Gaia",
    "Iris",
    "Eos",
    "Hercules",
    "Chronus",
    "Terminus",
    "Janus",
    "Sylvanus",
    "Odin",
    "Thor",
    "Loki",
    "Heimdall",
    "Baldr",
    "Hodur",
    "Hermod",
    "Frey",
    "Freya",
    "Forseti",
    "Bragi",
    "Hel",
    "Sif",
    "Frigga",
    "Tyr",
    "Njord",
    "Mimir",
    "Urd,",
    "Skuld",
    "Verandi",
    "Volla",
    "Vidar",
    "Ratatoskr",
    "Ra",
    "Khepri",
    "Osiris",
    "Anubis",
    "Isis",
    "Horus",
    "Set",
    "Bast",
    "Bes",
    "Sobek",
    "Nephthys",
    "Hathor",
    "Sekhmet",
    "Thoth",
    "Serqet",
    "Nepri",
    "Hapi",
    "Taweret",
    "Khonsu",
    "Medjed",
    "Kebechet",
    "Anhur",
    "Pakhet",
    "Ha",
    "Heh",
    "Nu",
    "Dua",
    "Min",
    "Shai",
    "Ptah",
    "Pan-Ku",
    "Shennong",
    "Nu Wa",
    "Yu Huang",
    "Sun Wukong",
    "Hou Tou",
    "Guan Yu",
    "Tian Mu",
    "Lei Gong",
    "Shou Hsing",
    "Xi Wangmu",
    "Kui Xing",
    "Zhu Rong",
    "Nezha",
    "Yen-Lo Wang",
    "Zao Shen",
    "Choy Sun Yeh",
    "Chang'e",
    "Eight Immortals",
    "Izanagi",
    "Izanami",
    "Amaterasu",
    "Tsukuyomi",
    "Susanoo",
    "Bishamon",
    "Hotei",
    "Ebisu",
    "Daikokuten",
    "Banzaiten",
    "Fukurokuju",
    "Jurōjin",
    "Inari",
    "Kaminari",
    "Raijin",
    "Fujin",
    "Kagutsuchi",
    "Ame-No-Mi-Kumari",
    "Amatsu-Mikaboshi",
    "Kuzenbo",
    "The Dagda",
    "Balor",
    "Angus",
    "Anpao",
    "Cerridwen",
    "Cernunnos",
    "Gwynn",
    "Danu",
    "Leir",
    "Fuamnach",
    "Bodb Derg",
    "Lugh",
    "Nuada",
    "Morrigan",
    "Arawn",
    "Badb",
    "Brigit",
    "Boann",
    "Taranis",
    "Artio",
    "Epona",
    "Cairbre",
    "Carman",
    "Dub",
    "Dother",
    "Dian",
    "Brahman",
    "Vishnu",
    "Shiva",
    "Kali-Ma",
    "Ganesha",
    "Ratli",
    "Yama",
    "Indra",
    "Agni",
    "Parvati",
    "Lakshmi",
    "Maya",
    "Kartikeya",
    "Ahura Mazda",
    "Mithras",
    "Ahriman",
    "Ametertat",
    "Atar",
    "Asha",
    "Armaiti",
    "Kshathra Vairya",
    "Vohu Manah",
    "Haurvatat",
    "Zurvan",
    "Gitche Manitou",
    "Hotamintanio",
    "Haokah",
    "Malsumis",
    "Calumet",
    "Nokomis",
    "Nanabozho",
    "Iktomi",
    "Owayodata",
    "Tawa",
    "Tomazooma",
    "Dzeharlons",
    "Kaiti",
    "Azeban",
    "Jiibayaabooz",
    "Hodiak",
    "Narya",
    "Nanuq",
    "Negafok",
    "Kadlu",
    "Nelvanna",
    "Turoq",
    "Sedna",
    "Tekkeitsertok",
    "Aipalovik Agloolik",
    "Quetzalcoatl",
    "Tezcatlipoca",
    "Huitzilopochtli",
    "Tlaloc",
    "Coatlicue",
    "Xipe Totec",
    "Ozomatli",
    "Xochipilli",
    "Xochiquetzal",
    "Michtlantecuhtli",
    "Xolotl",
    "Tonatiuh",
    "Huehuecoyotl",
    "Itzamna",
    "Hunab Ku",
    "Ixchel",
    "Wayep",
    "Chaac",
    "Ah Muzen Cab",
    "Awilix",
    "Hun Batz",
    "Acat",
    "Kukulkan",
    "Ah Kin Xoc",
    "Ixcacao",
    "Acan",
    "Ek Chuah",
    "Xbalanque",
    "Hunaphu",
    "Camazotz",
    "Ah-Puch",
    "Buluc Chabtan",
    "Mam",
    "Inti",
    "Chasca",
    "Kon",
    "Pachamama",
    "Viracocha",
    "Supay",
    "Mama Cocha",
    "Mama Quilla",
    "Urcuchillay",
    "Axomamma",
    "Kane Milohai",
    "Ku",
    "Lono",
    "Kanaloa",
    "Papa",
    "Ragni",
    "Namaka",
    "Whiro",
    "Pele",
    "Poliahu",
    "B'ngudja",
    "Ukanipo",
    "Kamohoalii",
    " God of stea",
    "Apukohai",
    "Lakakane",
    "Kuape",
    "Maui",
    "Altjira",
    "Baiame",
    "Julunggul",
    "Mamaragan",
    "Gnowee",
    "Marmoo",
    "Narahdarn",
    "Wambeen",
    "Bathala",
    "Apo Laki",
    "Mayari",
    "Tala",
    "Amihan",
    "Anitun",
    "Aswang",
    "Detinos",
    "Aman Sinaya",
    "Apo Angin",
    "Tengri",
    "Ulgen",
    "Vaat",
    "Kuara",
    "Ay",
    "Koyash",
    "Erlik",
    "Gesar",
    "Kyazaghan",
    "Umay",
    "Kayra",
    "Kurmez",
    "Murgen",
    "Kubai",
    "Ak Ana",
    "Ay-Ata",
    "Gun Ana",
    "Yel Ana",
    "Yel Ata",
    "Berkut",
    "Aisyt",
    "Su Ana",
    "Su Ata",
    "Od Ana",
    "Od Ata",
    "Yer Tanry",
    "Etuhen",
    "Jaiuk",
    "Alaz",
    "Baianai",
    "Adaghan",
    "Akbugha",
    "Shalyk",
    "Inehsit",
    "Uren",
    "Qovaq",
    "Zarlik",
    "Zada",
    "Ukulan",
    "Izih",
    "Chokqu",
    "Talai",
    "Svarog",
    "Veles",
    "Perun",
    "Stribog",
    "Svarozvich",
    "Milda",
    "Saule",
    "Marzanna",
    "Dazhbog",
    "Laima",
    "Lada",
    "Svantovit",
    "Chernobog",
    "Buluku",
    "Avlekete",
    "Ogun",
    "Shango",
    "Damballah",
    "Anansi",
    "Eschu",
    "Oshun",
    "Ghekre",
    "Lusa",
    "Mahu",
    "Legba",
    "Baron Samedi",
    "Annu",
    "Ba'al",
    "Eriskegal",
    "Inanna",
    "Dagon",
    "Martu",
    "Nergal",
    "Ningal",
    "Saja",
    "Ninhursag",
    "Tammuz",
    "Marduk",
    "Tiamat",
    "Apsu",
    "Ukko",
    "Äkräs",
    "Nyyrikki",
    "Tapio",
    "Tuoni",
    "Vammatar",
    "Ilmarinen",
    "Ahti",
    "Akka",
    "Ajatar",
    "Lempo",
    "Hwanin",
    "Munsin",
    "Nulgupjisin",
    "Cheuksin",
    "Eopsin",
    "Jowangsin",
    "Magu",
    "Sosamsin",
    "Teojusin",
    "Ungnyeo",
    "Jumong",
    "Sumyeong-Jangja",
    "Yondung Halmoni",
    "Allah",
    "Allat",
    "Aluzza",
    "Manat",
    "Hubal",
    "Wadd",
    "Suwa'",
    "Yaghuth",
    "Ya'uq",
    "Nasr",
    "Nuha",
    "Tupa",
    "Sume",
    "Guaraci",
    "Jaci",
    "Ceuci",
    "Akuanduba",
    "Iara",
    "Yeba Belo",
    "Anhanga",
    "Yorixiriamori",
    "Yahweh",
    "Satan",
    "Jesus Christ",
    "Saint Michael",
    "Saint Gabriel",
  ]